spring:
  data:
    mongodb:
      uri: ${MONGODB_SERVER}
  redis:
    host: localhost
    port: 6379

  output:
    ansi:
      enabled: always
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
  #    consumer:
  #      group-id: test # Consumer 그룹 ID
  #      auto-offset-reset: latest # 오프셋 초기화 정책
  #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer # 키 역직렬화 방법
  #      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer # 값 역직렬화 방법

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: ${BUCKET_NAME}
    region:
      static: ${REGION}
    stack:
      auto: false

logging:
  level:
    org.hibernate: info
    org.hibernate.SQL: info
    org.hibernate.type: info


jwt:
  secret: ${SECRET_KEY}
  access-token:
    header: Authorization
    expiration-time: 300000
  refresh-token:
    header: Authorization_refresh
    expiration-time: 600000

apple:
  team:
    id: ${APPLE_TEAM_ID}
  login:
    key: ${APPLE_LOGIN_KEY}
  client:
    id: ${APPLE_CLIENT_ID}
  private:
    key: ${APPLE_PRIVATE_KEY}

image:
  url: ${IMAGE_URL}
