spring:
  redis:
    host: localhost
    port: 6379

  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      root: debug

#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: ${KAKAO_CLIENT}
#            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
#            scope:
#              - account_email
#            client-authentication-method: client_secret_post
#            authorization-grant-type: authorization_code
#            client-name: kakao
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
jwt:
  secret: ${SECRET_KEY}
  access-token:
    #expire-length: 1800000
    header: Authorization
  refresh-token:
    #expire-length: 1209600000
    header: Authorization_refresh
#  redis:
#    host: localhost
#    port: 6379
