spring:
  redis:
    host: localhost
    port: 6379

  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate: info
    org.hibernate.SQL: debug
    org.hibernate.type: debug

jwt:
  secret: ${SECRET_KEY}
  access-token:
    header: Authorization
    expiration-time: 30
  refresh-token:
    header: Authorization_refresh
    expiration-time: 60
